### ISSUE TITLE
Brick is not working correctly

### ISSUE THREAD

**Issue by Hendrik1704** [JETSCAPE/JETSCAPE#153]
While testing the new implementation of the Hybrid Hadronization module, I ran into problems with the brick implementation.
When I use the attached xml file, the output states `Brick::GetHydroInfo(Jetscape::real,Jetscape::real,Jetscape::real,Jetscape::real,std::unique_ptr<Jetscape::FluidCellInfo>&):Hydro not run yet ...`  and the code is stopping. 
There is a `hydro_status` variable set to `FINISHED`, when the `EvolveHydro()` function is called, which is needed to get the medium information in `GetHydroInfo()`.

To me, it seems as if the `GetHydroInfo()` function in `Brick.cc` is called first, such that the if statement is false and the error is thrown.
I tried to add a `hydro_status = FINISHED;`  just before the if statement and then everything is working fine. However, this is only a temporary workaround to make it work.

I add the xml file here:
[jetscape_user_brick_test.txt](https://github.com/JETSCAPE/JETSCAPE/files/11761858/jetscape_user_brick_test.txt)

**Comment by jhputschke** [comment]
Okay, so there is nothing wrong with the Brick, however the modules in the xml have to be put in the correct order, meaning, the hydro xml tag has to come before the Eloss ... we did not implemented checks/automatic rearranging so far. 
So that's why the hydro did not got executed before the Eloss:
So the xml order has to be (maybe we should check if this is correct in all the ones in the config ...):


  <Hard>
          
    <PGun>
      <name>PGun</name>
      <pT>100</pT>
      <parID>1</parID>
    </PGun>
  </Hard>

  
  <Hydro>
          <deltaT>0.1</deltaT>
          <formTime> -0.1</formTime>
          <maxT>20</maxT>
          <tStart> 0.6 </tStart> 
          <AddLiquefier> false </AddLiquefier>

    
    <Brick bjorken_expansion_on="false" start_time="0.6">
      <name>Brick</name>
      <T>0.3</T>
    </Brick>
  </Hydro>
  
  
  <Eloss>
...

**Comment by jhputschke** [comment]
PS: Assuming you use runJetscape and steer everything via xml. If you use a separate executable which has things in the correct order in the code, then the order in the xml does not matter ...

**Comment by Hendrik1704** [comment]
With the switched order in the xml file it's working.
