### ISSUE TITLE
AdS/CFT module does not write correct parton shower output

### ISSUE THREAD

**Issue by jdmulligan** [JETSCAPE/JETSCAPE#39]
The AdS/CFT module only writes out the shower-initiating parton to the output file -- and none of the parton shower. 

Thanks to @wilkeqgp for reporting.

After some small digging: The reason is the same issue report in #31. In JETSCAPE 2.0, the two-stage hydro developments changed the framework to require that parton splittings are 1-->2 processes in order for them to be written to the output. The 1-->1 processes will not be written. The AdS/CFT module however always returns a 1-->1 process, so despite that the module performs energy loss none of these processes are written to the output file.

@chunshen1987 @peibols

**Comment by peibols** [comment]
Best will be to introduce a source term with the amount of energy and momentum loss. That should effectively be a 1->2 process, right?

**Comment by chunshen1987** [comment]
You can try to attach the Liquefier to the jet energy loss modules. It will add the missing soft parton by checking the energy-momentum conservation at every vertex.

**Comment by jdmulligan** [comment]
Hi @peibols ,

Any update on a fix to this? It seems to me that adding the recoil/source particles is a reasonable solution -- otherwise @chunshen1987 and the PHYS group have to be convinced to re-work the 1-->2 requirement introduced with the Liquefier (I don't think we want to _require_ that one has to use the Liquefier in order for AdS/CFT to work).

**Comment by peibols** [comment]
Hi @jdmulligan ,
I just pushed a branch called ads_fix that has fixed two issues:

1. It now assigns kinematics consistent with massive partons - it would produce unwanted behaviour otherwise.

2. Missing momentum is added within AdS eloss module, so that Liquefier is not actually required.

When I was debugging I got into SegFaults that happen in Hybrid Hadronization when there is no final parton at all present, I believe. I put a couple of check conditions where the code was crashing, but I would suggest @mkordell to have a look to see if it makes sense.

I had to make a small change in JetEnergyLoss.cc, so that partons from pOutTemp with stat = miss_stat are not added even if there is no Liquefier.

**Comment by jdmulligan** [comment]
Hi @peibols Excellent, thank you!

@mkordell Can you please have a look whether these modifications are okay to you?

**Comment by mkordell** [comment]
Hi,

I wasn't aware that running hybridhadronization on an empty event would segfault.  The changes I see made, look ok to me; I see what went wrong.

With that in mind, I should probably include a fix that will 'skip' trying to hadronize an empty event, but I'll wait to include that until the next update to hybridhadronization.

Thanks!

**Comment by jdmulligan** [comment]
Fixed in release 3.0.2
https://github.com/JETSCAPE/JETSCAPE/commit/9431741859e6876b9cd76ac2b0ddbd6b4c060025
