### ISSUE TITLE
Header file conflict

### ISSUE THREAD

**Issue by K-JW** [JETSCAPE/JETSCAPE#40]
Looking at the source code, we can find that `MUSIC` has a header file `data_struct.h` and `iSS`also has a header file with the same name. When using `make install` to install, these two header files will be copied to the same directory, causing header file conflicts.

Another problem is that after executing the `make install` command, all header files in `src/preequilibrium` are not copied to the `${CMAKE_INSTALL_PREFIX}/include` directory.

------------------------
## Other Info:

- My platform : 
   - System: *Ubuntu 18.04 x86_64*
   - CMAKE : *v3.10.2*
   - GCC : *v7.5.0*
- JETSCAPE version : *v3.0.1*
- Configuration : `cmake .. -DUSE_MUSIC=ON -DUSE_ISS=ON -DUSE_FREESTREAM=ON -DCMAKE_INSTALL_PREFIX=/home/.hep`

**Comment by jdmulligan** [comment]
Hi @K-JW 

Thanks for your issue -- at the moment we do not support `make install` but rather one should simply use `make` to build locally. Please let us know if there is a particular reason you need `make install`, we could possibly add support for that in the future -- otherwise give `make` a try and let us know if you have any further issues.

Best,
James
