### ISSUE TITLE
SMASH/PYTHIA version compatibility

### ISSUE THREAD

**Issue by jdmulligan** [JETSCAPE/JETSCAPE#81]
Hi All,

This thread is to discuss our treatment of which versions of SMASH and PYTHIA are used by JETSCAPE.

The current version of [SMASH](https://github.com/smash-transport/smash), 2.0, requires PYTHIA 8.303.
The "old" version of SMASH, 1.8, requires PYTHIA 8.235.

In the current release of JETSCAPE, we use SMASH 1.8 and PYTHIA 8.235 by default. 
Note that the user can also easily change these: you can change the SMASH version according to the download script `get_smash.sh`, and you can install any version of PYTHIA that you like. That is, it is relatively minimal work for a user to use the new versions of SMASH and PYTHIA.

However, if there is an incompatibility in the default treatment, our automated build tests will fail:
- If incompatible SMASH/PYTHIA versions are used, the build test will crash
- If the new versions of SMASH/PYTHIA are used, the "exact" regression test will fail to changes in PYTHIA, yet to be investigated. 

The ideal solution, physics-wise, is likely to check that we understand the PYTHIA updates, and then switch our default usage to the new versions of SMASH and PYTHIA. At present, this is our tentative plan. All comments welcome and appreciated!

@amajumder @bardelch @doliinychenko @justinmohs

**Comment by jdmulligan** [comment]
For reference, test plots from the recent SMASH update to PYTHIA 8.303: http://theory.gsi.de/~smash/analysis_suite/SMASH-2.0.1/energy_scan/

**Comment by jdmulligan** [comment]
Hi All,

We will go ahead and try to increase the PYTHIA/SMASH versions for our next release (specifically in #102). 

I currently seem to get an error building SMASH however -- using PYTHIA 8.303 and SMASH 2.0.2: https://github.com/JETSCAPE/JETSCAPE/pull/102/checks?check_run_id=3283733481

@stdnmr @justinmohs @elfnerhannah any ideas? or did I use the correct SMASH version?

Thanks,
James

**Comment by stdnmr** [comment]
Sorry @jdmulligan it seems like the @ mention got somehow lost in my notifications. What is the status on error? Do you still see the error on build?

In the checks on #102 it looks like the compiler does not like the integer notation with the thousands separator e..g `1'000'000'000`.

**Comment by stdnmr** [comment]
Just to update this thread: We will switch to an even newer Pythia version (8.307) with the next SMASH release `SMASH-2.2`. I already tried to build the newest SMASH version (close to what will be 2.2) with the current JETSCAPE main and there are only minor changes to be made, since some function calls changed. In particular, this means that SMASH should still be backwards compatible with JETSCAPE even with all newer developments.

I pushed the necessary changes to the SMASH wrapping to [this branch](https://github.com/stdnmr/JETSCAPE/tree/stdnmr/updates-smash).

For my tests, I however tried to not update the Pythia version of Jetscape itself, but just downloaded Pythia 8.307 and use it in parallel for SMASH. This worked for version 8.303, but for 8.307 I am getting linking issue. I assume this happens, since some function calls for Pythia also changed. Ideally we would anyway not introduce this inconsistency of two different Pythia version, but Jetscape also updates to the newer Pythia version. Still this is something to keep in mind here.
